//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #componentName:componentCost:componentTDP:frequencyMhz:instructionsPerCycle:numOfCores
        ///cpu1:71,78:65:2333:4:2
        ///cpu2:85,71:70:3000:4:2
        ///cpu3:62,21:75:2333:8:2
        ///cpu4:75,00:80:3000:8:2
        ///cpu5:125,46:85:2666:4:4
        ///cpu6:142,22:90:3200:4:4
        ///cpu7:126,32:95:3000:8:4
        ///cpu8:180,00:100:4500:8:4
        ///cpu9:228,57:105:3000:4:8
        ///cpu10:327,27:110:4500:4:8
        ///cpu11:185,46:115:2666:8:8
        ///cpu12:177,73:120:2666:8:8
        ///cpu13:384,00:125:3000:8:16
        ///cpu14:492,31:130:4000:8:16
        ///cpu15:379,26:135:3200:16:16
        ///cpu16:388,57:140:3400:16:16
        ///#.
        /// </summary>
        internal static string cpus {
            get {
                return ResourceManager.GetString("cpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #componentName:componentCost:componentTDP:vramGB,sfpTFLOPS,dfpTFLOPS
        ///gpu1:117,65:200,00:2,00:2,00:1,18
        ///gpu2:123,53:210,00:2,00:2,35:1,38
        ///gpu3:129,41:220,00:2,00:2,70:1,59
        ///gpu4:135,29:230,00:2,00:3,05:1,79
        ///gpu5:141,18:240,00:4,00:3,40:2,00
        ///gpu6:147,06:250,00:4,00:3,75:2,21
        ///gpu7:152,94:260,00:4,00:4,10:2,41
        ///gpu8:158,82:270,00:4,00:4,45:2,62
        ///gpu9:164,71:280,00:8,00:4,80:2,82
        ///gpu10:170,59:290,00:8,00:5,15:3,03
        ///gpu11:176,47:300,00:8,00:5,50:3,24
        ///gpu12:182,35:310,00:8,00:5,85:3,44
        ///gpu13:188,24:320,00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gpus {
            get {
                return ResourceManager.GetString("gpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap havard_bjerke_8372550635 {
            get {
                object obj = ResourceManager.GetObject("havard_bjerke_8372550635", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #componentName:componentCost:componentTDP:capacityGB:frequencyMhz
        ///mem1:40:4:2:1333
        ///mem2:50:4:2:1600
        ///mem3:60:4:2:1866
        ///mem4:70:4:2:2400
        ///mem5:80:6:4:1333
        ///mem6:90:6:4:1600
        ///mem7:100:6:4:1866
        ///mem8:110:6:4:2400
        ///mem9:120:8:8:1333
        ///mem10:130:8:8:1600
        ///mem11:140:8:8:1866
        ///mem12:150:8:8:2400
        ///mem13:160:10:16:1333
        ///mem14:170:10:16:1600
        ///mem15:180:10:16:1866
        ///mem16:190:10:16:2400
        ///#.
        /// </summary>
        internal static string mems {
            get {
                return ResourceManager.GetString("mems", resourceCulture);
            }
        }
    }
}
